BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"
BBFILE_COLLECTIONS += "secure-signing"
BBFILE_PATTERN_secure-signing = "^${LAYERDIR}/"
BBFILE_PRIORITY_secure-signing = "8"